/**:
  ros__parameters:
    pos_tracking:
      pos_tracking_enabled: true
      odometry_frame: 'odom'
      map_frame: 'map'
      two_d_mode: true
      imu_fusion: true
      publish_tf: false
      publish_map_tf: false
      set_gravity_as_origin: false
      reset_odom_with_loop_closure: false
      publish_3d_landmarks: true  # publish SLAM landmarks as PointCloud2 on pose/landmarks
      publish_lm_skip_frame: 5
      area_memory: false          # overridden by zed.launch.py when slam_mode!=off
      area_file_path: ''          # overridden by zed.launch.py area_file arg
      enable_localization_only: false
      save_area_memory_on_closing: false

    object_detection:
      od_enabled: false           # overridden by zed.launch.py od:=true
      enable_tracking: true
      detection_model: 'MULTI_CLASS_BOX_FAST'
      max_range: 10.0
      filtering_mode: 'NMS3D'
      prediction_timeout: 2.0
      allow_reduced_precision_inference: true
      class:
        people:
          enabled: true
          confidence_threshold: 65.0
        vehicle:
          enabled: true
          confidence_threshold: 60.0
        bag:
          enabled: false
          confidence_threshold: 40.0
        animal:
          enabled: false
          confidence_threshold: 40.0
        electronics:
          enabled: false
          confidence_threshold: 45.0
        fruit_vegetable:
          enabled: false
          confidence_threshold: 50.0
        sport:
          enabled: false
          confidence_threshold: 30.0
